# Generated by Django 4.2.4 on 2023-09-17 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('seats', models.IntegerField(default=0, verbose_name='nombre de places')),
            ],
            options={
                'verbose_name': 'Chauffeur',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Groupe de coureurs',
                'verbose_name_plural': 'Groupes de coureurs',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gpx', models.FileField(upload_to='gpx/', verbose_name='fichier GPX')),
                ('datetime_start', models.DateTimeField(verbose_name='date et heure de départ')),
                ('datetime_stop', models.DateTimeField(verbose_name="date et heure d'arrivée")),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude de départ')),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude de départ')),
                ('stop_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name="latitude d'arrivée")),
                ('stop_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name="longitude d'arrivée")),
                ('full', models.BooleanField(default=False, verbose_name='tronçon complet')),
            ],
            options={
                'verbose_name': 'Tronçon',
            },
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('progress', models.FloatField(default=0.0, verbose_name='avancement')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='certificat médical')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='course_drapeau.group')),
            ],
            options={
                'verbose_name': 'Coureur',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='sections',
            field=models.ManyToManyField(blank=True, to='course_drapeau.section', verbose_name='tronçons'),
        ),
    ]
