# Generated by Django 4.2.4 on 2023-09-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_drapeau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='payé'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='certificat médical de moins de 1 an'),
        ),
    ]
