# Generated by Django 4.2.4 on 2023-08-27 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_drapeau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='course_drapeau.group'),
        ),
    ]
