# Generated by Django 4.2.4 on 2023-09-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_drapeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100, verbose_name='question')),
                ('answer', models.CharField(max_length=100, verbose_name='réponse')),
            ],
            options={
                'verbose_name': 'Information',
            },
        ),
    ]
