# Generated by Django 4.2.4 on 2023-09-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_drapeau', '0002_runner_paid_alter_runner_medical_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='license',
            field=models.BooleanField(blank=True, null=True, verbose_name='permis de conduire'),
        ),
        migrations.AddField(
            model_name='runner',
            name='manual_gearbox',
            field=models.BooleanField(blank=True, null=True, verbose_name='boîte manuelle'),
        ),
        migrations.AddField(
            model_name='runner',
            name='vegetarian',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='végétarien'),
        ),
        migrations.AddField(
            model_name='runner',
            name='young_driver',
            field=models.BooleanField(blank=True, null=True, verbose_name='jeune conducteur'),
        ),
    ]
