# Generated by Django 4.2.4 on 2023-08-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_drapeau', '0002_alter_runner_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='progress',
            field=models.FloatField(default=0.0, verbose_name='avancement'),
        ),
    ]
