# Generated by Django 4.2.4 on 2023-09-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_drapeau', '0002_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='datetime_start',
            field=models.DateTimeField(null=True, verbose_name='date et heure de départ'),
        ),
        migrations.AlterField(
            model_name='section',
            name='datetime_stop',
            field=models.DateTimeField(null=True, verbose_name="date et heure d'arrivée"),
        ),
    ]
