# Generated by Django 4.2.4 on 2023-09-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_drapeau', '0003_alter_section_datetime_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Parcours',
            },
        ),
        migrations.AlterField(
            model_name='section',
            name='datetime_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date et heure de départ'),
        ),
        migrations.AlterField(
            model_name='section',
            name='datetime_stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date et heure d'arrivée"),
        ),
        migrations.AddField(
            model_name='section',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course_drapeau.route'),
            preserve_default=False,
        ),
    ]
