# Generated by Django 4.2.4 on 2023-10-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_drapeau', '0003_runner_license_runner_manual_gearbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='runner',
            name='vegetarian',
            field=models.BooleanField(blank=True, null=True, verbose_name='végétarien'),
        ),
    ]
