# Generated by Django 4.2.4 on 2023-09-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_drapeau', '0005_alter_route_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Parcour'},
        ),
    ]
