# Generated by Django 4.2.4 on 2023-09-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_drapeau', '0006_alter_route_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Parcours'},
        ),
    ]
